export const DATA = {
  name: "Vaasu Nikhil Bobba",
  firstName: "Nikhil",
  lastName: "Bobba",
  role: "AI Engineer & Pragmatic Innovator",
  location: "Groton, CT",
  tagline: "I build dependable software that thinks for itself.",
  bio: `AI engineer and recent Master's graduate from UWM with a B.Tech in Electrical & Electronics. I architect resilient AI pipelines, ship reliable code, and translate technical complexity into business clarity. My approach blends systems thinking, disciplined engineering, and creative heuristics — from design to delivery of AI-driven automation that transforms uncertainty into repeatable outcomes.`,
  email: "bobbanikhil@gmail.com",
  social: {
    github: "https://github.com/bobbanikhil",
    linkedin: "https://www.linkedin.com/in/vaasu-nikhil-bobba-98324312b/",
  },
  stats: [
    { label: "GPA", value: "3.9" },
    { label: "Efficiency↑", value: "95%" },
    { label: "Years Exp.", value: "4+" },
    { label: "Projects", value: "6+" },
  ],
  nav: [
    { label: "Work", href: "#work" },
    { label: "Experience", href: "#experience" },
    { label: "Skills", href: "#skills" },
    { label: "Playground", href: "#playground" },
    { label: "Contact", href: "#contact" },
  ],
  projects: [
    {
      title: "U-NO-CODE",
      tagline: "Azure AI Hackathon Winner — Autonomous Pipeline",
      description: "Led winning team developing an autonomous multimodal AI pipeline for creating and managing the full lifecycle of hackathons. Implemented real-time data processing and ML models for automated decision-making, increasing efficiency by over 95%.",
      tags: ["Azure AI", "Python", "ML", "Automation"],
      impact: "95% efficiency boost",
      badge: "🏆 Hackathon Winner",
      color: "#6366f1",
      github: "https://github.com/bobbanikhil",
      live: "#",
    },
    {
      title: "YECS",
      tagline: "AI-Powered Credit Scoring for Young Entrepreneurs",
      description: "Engineered a full-stack AI-powered credit scoring system using React, Flask, and Gemini Pro API. Features a conversational AI copilot for personalized financial guidance and novel alternative data models. 41% higher approval rate for first-time entrepreneurs while reducing default risk by 38%.",
      tags: ["React", "Flask", "Gemini Pro", "FinTech"],
      impact: "41% higher approvals",
      badge: "🧠 AI FinTech",
      color: "#f59e0b",
      github: "https://github.com/bobbanikhil",
      live: "#",
    },
    {
      title: "VENVT AI",
      tagline: "1 AI Agent = 10 QA Engineers",
      description: "Developed a comprehensive AI testing agentic framework using Python, TensorFlow, and cloud technologies. Low-code test automation with self-healing locators and AI-stabilized test maintenance. Incredibly fast authoring that lets teams scale automation effortlessly.",
      tags: ["Python", "TensorFlow", "AI Agents", "CI/CD"],
      impact: "10x engineer output",
      badge: "🤖 Agentic Testing",
      color: "#22c55e",
      github: "https://github.com/bobbanikhil",
      live: "#",
    },
    {
      title: "Spectrum AI Pro",
      tagline: "Real-Time Accessibility for Colorblind Users",
      description: "Chrome extension using Chrome's built-in AI for intelligent color overlays. Zero latency — runs entirely on-device using Chrome AI APIs. Designed for real-world accessibility without cloud dependency.",
      tags: ["Chrome AI", "JavaScript", "Accessibility"],
      impact: "100% on-device",
      badge: "♿ Accessibility AI",
      color: "#ec4899",
      github: "https://github.com/bobbanikhil",
      live: "#",
    },
  ],
  experiences: [
    {
      role: "AI Engineer",
      company: "I2E Consulting",
      location: "Groton, CT",
      period: "Jun 2025 – Present",
      bullets: [
        "Architected dynamic content generators using n8n for robust workflow orchestration, integrating multiple LLM APIs",
        "Deployed enterprise AI accelerators redefining daily operations by embedding AI into routine problem-solving",
        "Proactively collaborating with the team on new features and system designs",
      ],
      current: true,
    },
    {
      role: "QA Tester",
      company: "Pfizer",
      location: "Groton, CT",
      period: "Oct 2025 – Present",
      bullets: [
        "Collaborated with cross-functional teams to define requirements, increasing overall team performance by 30%",
        "Managed data-driven projects with detailed documentation, stakeholder updates, and performance reporting",
        "Created dashboards and reports from raw data for better business decision-making",
      ],
      current: true,
    },
    {
      role: "Event Manager",
      company: "Peck School of the Arts, UWM",
      location: "Milwaukee, WI",
      period: "May 2024 – May 2025",
      bullets: [
        "Coordinated 150+ university events including recruitment sessions, exhibitions, and workshops",
        "Streamlined ticketing system bringing efficiency up to 90%",
        "Collected and analyzed participant feedback to evaluate program effectiveness",
      ],
      current: false,
    },
    {
      role: "Software / Data Engineer",
      company: "Capgemini",
      location: "Mumbai, India",
      period: "May 2022 – Jul 2023",
      bullets: [
        "Built full stack solutions increasing overall growth by 30%",
        "Generated visual reports and dashboards from raw uncleaned data for business decisions",
        "Played key role in data-driven projects with stakeholder updates and performance reporting",
      ],
      current: false,
    },
  ],
  education: [
    {
      degree: "M.S. Information Technology Management",
      school: "University of Wisconsin, Milwaukee",
      period: "Sep 2023 – May 2025",
      gpa: "3.9 / 4.0",
      focus: "AI & Data Analytics",
    },
    {
      degree: "B.Tech Electrical & Electronics Engineering",
      school: "Reva University, India",
      period: "Jun 2018 – Aug 2022",
      focus: "Minor: Computer Science",
    },
  ],
  skills: {
    "AI & Machine Learning": ["Python", "TensorFlow", "PyTorch", "Gemini Pro", "n8n", "Chrome AI", "pandas", "NumPy"],
    "Full-Stack & Frontend": ["React", "TypeScript", "JavaScript", "Java", "Flask", "RESTful APIs", "HTML/CSS"],
    "Data & Cloud": ["Snowflake", "SQL", "MySQL", "PostgreSQL", "MongoDB", "AWS", "Azure", "Docker", "Kubernetes"],
    "Analytics & BI": ["Tableau", "Power BI", "Google Data Studio", "Alteryx", "Databricks", "Jupyter", "R"],
    "QA & DevOps": ["JIRA", "Git", "CI/CD", "Agile", "Scrum", "SDLC", "UAT", "Regression Testing"],
  },
  commands: [
    { label: "View Projects", section: "#work", icon: "grid" },
    { label: "Experience", section: "#experience", icon: "briefcase" },
    { label: "Skills", section: "#skills", icon: "zap" },
    { label: "Playground", section: "#playground", icon: "gamepad" },
    { label: "Contact", section: "#contact", icon: "mail" },
    { label: "GitHub", section: "https://github.com/bobbanikhil", icon: "github", external: true },
    { label: "LinkedIn", section: "https://www.linkedin.com/in/vaasu-nikhil-bobba-98324312b/", icon: "linkedin", external: true },
    { label: "Download Resume", section: "#", icon: "download" },
  ],
};
